# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DataColumnConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('arguments', models.TextField()),
                ('validation_schema', models.TextField()),
                ('data_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dqc.DataColumn')),
            ],
        ),
        migrations.CreateModel(
            name='DataQualityDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('connection_drive', models.CharField(max_length=200)),
                ('connection_server', models.CharField(max_length=200)),
                ('connection_port', models.CharField(max_length=200)),
                ('connection_database', models.CharField(max_length=200)),
                ('connection_user', models.CharField(max_length=200)),
                ('connection_password', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DataSetEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('found_problems', models.IntegerField()),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dqc.DataSet')),
            ],
        ),
        migrations.CreateModel(
            name='DataSetEvaluationProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('data_column_constraint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dqc.DataColumnConstraint')),
                ('data_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dqc.DataRecord')),
                ('data_set_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dqc.DataSetEvaluation')),
            ],
        ),
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dqc.DataSet')),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DataValidationConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('method_to_call', models.CharField(max_length=200)),
                ('arguments_number', models.IntegerField()),
                ('arguments_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dqc.DataType')),
            ],
        ),
        migrations.AddField(
            model_name='datarecord',
            name='data_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dqc.DataTable'),
        ),
        migrations.AddField(
            model_name='datacolumnconstraint',
            name='data_validation_constraint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dqc.DataValidationConstraint'),
        ),
        migrations.AddField(
            model_name='datacolumn',
            name='data_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dqc.DataTable'),
        ),
        migrations.AddField(
            model_name='datacolumn',
            name='data_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dqc.DataType'),
        ),
    ]
