# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dqc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('DataSet', 'connection_drive', 'connection_driver')
    ]
