# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dqc', '0002_auto_20160317_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='datavalidationconstraint',
            name='data_quality_dimension',
            field=models.ManyToManyField(to='dqc.DataQualityDimension'),
        ),
        migrations.AddField(
            model_name='datavalidationconstraint',
            name='data_type',
            field=models.ManyToManyField(to='dqc.DataType'),
        ),
        migrations.AlterField(
            model_name='datacolumn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='datacolumnconstraint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='datasetevaluation',
            name='finished_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='datasetevaluation',
            name='found_problems',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='datasetevaluation',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='datavalidationconstraint',
            name='arguments_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='argument_type', to='dqc.DataType'),
        ),
    ]
