# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dqc', '0003_auto_20160324_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='connection_driver',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('pgsql', 'PostgreSQL'), ('mssql', 'Microsoft SQL Server')], max_length=200),
        ),
        migrations.AlterField(
            model_name='datasetevaluationproblem',
            name='data_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dqc.DataRecord'),
        ),
    ]
